#!/bin/bash

. rrd-stats.conf create || exit 3

# Genereer de grafieken voor de cpu load.
# Zet een bovengrens voor de grafiek anders weet rrdtool niet hoe die de
# Y-as moet schalen. Twee cpu's kan algauw een load van 2 geven, dus 2 is
# een mooie bovengrens. Bij een eventuele overschrijding zal rrdtool de
# schaal automatisch aanpassen.

titel=( "Swap usage the past day" \
	"Swap usage the past week" \
	"Swap usage the past month")

cd $STATSDIR
files=$(ls *-swapspace.rrd)

for rrdfile in $files; do

	hostname=$(get_hostname $rrdfile)

	filenaam=("${pngdir}/${hostname}-swapusage-day.png"	\
		"${pngdir}/${hostname}-swapusage-week.png"	\
		"${pngdir}/${hostname}-swapusage-month.png")

	echo "Swap usage" > ${pngdir}/${hostname}-swapusage.header

	for i in 0 1 2; do
		rrdtool graph ${filenaam[$i]}                 \
		--start ${START_TIMES[$i]} --end $END_TIME    \
		--vertical-label 'Swap used %'                \
		--title "${titel[$i]}"                        \
		--height $GRAPH_HEIGHT                        \
		--width $GRAPH_WIDTH                          \
		--upper-limit 100                             \
		--lower-limit 0                               \
		--rigid                                       \
		DEF:swap=${rrdfile}:swapspace:MAX             \
		LINE2:swap#00FF00:"swap used"                 > /dev/null 2>&1
	done
done

